"""add subscription_started

Revision ID: 06295666efc5
Revises: 05af44639cf3
Create Date: 2026-03-28 12:24:41.736362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06295666efc5'
down_revision = '05af44639cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_started', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('subscription_started')

    # ### end Alembic commands ###
