"""fresh

Revision ID: 12821b2e42ea
Revises: 
Create Date: 2026-03-27 09:22:45.389536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12821b2e42ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('office_address', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('kyc_status', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.Column('name3', sa.String(length=3), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=35), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('height', sa.String(length=10), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('birth_place', sa.String(length=50), nullable=True),
    sa.Column('birth_time', sa.String(length=20), nullable=True),
    sa.Column('profession', sa.String(length=50), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('caste', sa.String(length=50), nullable=True),
    sa.Column('community', sa.String(length=50), nullable=True),
    sa.Column('mother_tongue', sa.String(length=30), nullable=True),
    sa.Column('religion', sa.String(length=30), nullable=True),
    sa.Column('city', sa.String(length=25), nullable=True),
    sa.Column('state', sa.String(length=25), nullable=True),
    sa.Column('location', sa.String(length=50), nullable=True),
    sa.Column('profile_photo_url', sa.Text(), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('subscription_active', sa.Boolean(), nullable=True),
    sa.Column('subscription_expiry', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('disputes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('raised_by_user', sa.String(length=36), nullable=True),
    sa.Column('raised_by_agent', sa.String(length=36), nullable=True),
    sa.Column('against', sa.String(length=36), nullable=True),
    sa.Column('ticket_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['against'], ['users.id'], ),
    sa.ForeignKeyConstraint(['raised_by_agent'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['raised_by_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proposals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('client_id', sa.String(length=36), nullable=True),
    sa.Column('profile_ids', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    op.drop_table('payments')
    op.drop_table('disputes')
    op.drop_table('users')
    op.drop_table('agents')
    op.drop_table('admins')
    # ### end Alembic commands ###
